name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [28]
        target: [default]
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: run espresso test 
      uses: ReactiveCircus/android-emulator-runner@v2.24.0
      with:
        api-level: 29
        target: default
        arch: x86_64
        profile: nexus_6
        script: ./gradlew connectedDebugAndroidTest -Pcucumber -Ptags="@e2e"
